#include "Shader.h"

#include "Obelisk/Obelisk.h"

namespace ignis
{
	Shader::Shader(const std::string& vert, const std::string& frag)
	{
		m_program = CreateShaderProgram({
			{ GL_VERTEX_SHADER, obelisk::ReadFile(vert) }, 
			{ GL_FRAGMENT_SHADER, obelisk::ReadFile(frag) } 
			});
	}

	Shader::Shader(const std::string& vert, const std::string& geom, const std::string& frag)
	{
		m_program = CreateShaderProgram({
			{ GL_VERTEX_SHADER, obelisk::ReadFile(vert) },
			{ GL_GEOMETRY_SHADER, obelisk::ReadFile(geom) },
			{ GL_FRAGMENT_SHADER, obelisk::ReadFile(frag) }
			});
	}

	Shader::~Shader()
	{
		glDeleteProgram(m_program);
	}

	void Shader::Use()
	{
		DEBUG_ASSERT(glIsProgram(m_program), "[SHADER] Program handle does not refer to an object generated by OpenGL.");
		glUseProgram(m_program);
	}

	void Shader::SetUniform1i(const std::string& name, int value) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniform1i(location, value);
	}

	void Shader::SetUniform1f(const std::string& name, float value) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniform1f(location, value);
	}

	void Shader::SetUniform2f(const std::string& name, const glm::vec2& vector) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniform2fv(location, 1, &vector[0]);
	}

	void Shader::SetUniform3f(const std::string& name, const glm::vec3& vector) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniform3fv(location, 1, &vector[0]);
	}

	void Shader::SetUniform4f(const std::string& name, const glm::vec4& vector) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniform4fv(location, 1, &vector[0]);
	}

	void Shader::SetUniformMat2(const std::string& name, const glm::mat4& matrix) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniformMatrix2fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	void Shader::SetUniformMat3(const std::string& name, const glm::mat4& matrix) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniformMatrix3fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	void Shader::SetUniformMat4(const std::string& name, const glm::mat4& matrix) const
	{
		int location = GetUniformLocation(name);

		if (location < 0)
			DEBUG_WARN("[SHADER] Uniform {0} not found", name);
		else
			glUniformMatrix4fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	int Shader::GetUniformLocation(const std::string& name) const
	{
		return glGetUniformLocation(m_program, name.c_str());
	}

	void Shader::SetUniform1i(int location, int value) const
	{
		glUniform1i(location, value);
	}

	void Shader::SetUniform1f(int location, float value) const
	{
		glUniform1f(location, value);
	}

	void Shader::SetUniform2f(int location, const glm::vec2& vector) const
	{
		glUniform2fv(location, 1, &vector[0]);
	}

	void Shader::SetUniform3f(int location, const glm::vec3& vector) const
	{
		glUniform3fv(location, 1, &vector[0]);
	}

	void Shader::SetUniform4f(int location, const glm::vec4& vector) const
	{
		glUniform4fv(location, 1, &vector[0]);
	}

	void Shader::SetUniformMat2(int location, const glm::mat4& matrix) const
	{
		glUniformMatrix2fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	void Shader::SetUniformMat3(int location, const glm::mat4& matrix) const
	{
		glUniformMatrix3fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	void Shader::SetUniformMat4(int location, const glm::mat4& matrix) const
	{
		glUniformMatrix4fv(location, 1, GL_FALSE, &matrix[0][0]);
	}

	// Shader utils
	uint CreateShaderProgram(std::map<uint, const std::string&> shaderSrc)
	{
		uint program = glCreateProgram();
		std::vector<uint> attachedShader;

		for (auto& [type, src] : shaderSrc)
		{
			uint shader = CompileShader(type, src);

			if (shader == 0)
			{
				glDeleteProgram(program);
				return 0;
			}

			glAttachShader(program, shader);
			attachedShader.push_back(shader);
		}

		glLinkProgram(program);

		for (auto& shader : attachedShader)
		{
			glDeleteShader(shader);
			glDetachShader(program, shader);
		}

		GLint result = GL_FALSE;
		glGetProgramiv(program, GL_LINK_STATUS, &result);
		if (result == GL_FALSE)
		{
			DEBUG_ERROR("[SHADER] Linking Error");
			DEBUG_ERROR("[SHADER] {0}", GetProgramLog(program));
			glDeleteProgram(program);
			return 0;
		}

		glValidateProgram(program);

		result = GL_FALSE;
		glGetProgramiv(program, GL_VALIDATE_STATUS, &result);
		if (result == GL_FALSE)
		{
			DEBUG_ERROR("[SHADER] Validating Error");
			DEBUG_ERROR("[SHADER] {0}", GetProgramLog(program));
			glDeleteProgram(program);

			return 0;
		}

		return program;
	}

	uint CompileShader(uint type, const std::string& source)
	{
		if (source.empty())
		{
			DEBUG_ERROR("[SHADER] Shader source is missing for {0}", GetShaderType(type));
			return 0;
		}

		uint shader = glCreateShader(type);

		const char* data = source.c_str();
		glShaderSource(shader, 1, &data, nullptr);
		glCompileShader(shader);

		GLint result = GL_FALSE;
		glGetShaderiv(shader, GL_COMPILE_STATUS, &result);
		if (result == GL_FALSE)
		{
			DEBUG_ERROR("[SHADER] Compiling Error ({0})", GetShaderType(type));
			DEBUG_ERROR("[SHADER] {0}", GetShaderLog(shader));
			glDeleteShader(shader);

			return 0;
		}

		return shader;
	}

	std::string GetShaderLog(uint object)
	{
		GLint logLength = 0;

		if (!glIsShader(object))
			return "Failed to log: Object is not a shader";

		glGetShaderiv(object, GL_INFO_LOG_LENGTH, &logLength);

		std::vector<GLchar> log(logLength);

		glGetShaderInfoLog(object, logLength, &logLength, &log[0]);

		return std::string(&log[0], logLength - 1);
	}

	std::string GetProgramLog(uint object)
	{
		GLint logLength = 0;

		if (!glIsProgram(object))
			return "Failed to log: Object is not a program";

		glGetProgramiv(object, GL_INFO_LOG_LENGTH, &logLength);

		std::vector<GLchar> log(logLength);

		glGetProgramInfoLog(object, logLength, &logLength, &log[0]);

		return std::string(&log[0], logLength - 1);
	}

	std::string GetShaderType(uint type)
	{
		switch (type)
		{
		case GL_COMPUTE_SHADER:
			return "GL_COMPUTE_SHADER";
		case GL_VERTEX_SHADER:
			return "GL_VERTEX_SHADER";
		case GL_TESS_CONTROL_SHADER:
			return "GL_TESS_CONTROL_SHADER";
		case GL_TESS_EVALUATION_SHADER:
			return "GL_TESS_EVALUATION_SHADER";
		case GL_GEOMETRY_SHADER:
			return "GL_GEOMETRY_SHADER";
		case GL_FRAGMENT_SHADER:
			return "GL_FRAGMENT_SHADER";
		}

		return "INVALID_SHADER_TYPE";
	}
}